version: '2'
services:
  mariadb:
    image: k0st/alpine-mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: cattle 
      MYSQL_USER: cattle
      MYSQL_PASSWORD: cattle
      # MYSQL_ROOT_PASSWORD: 
    ports:
      - "3306:3306"
    volumes_from:
      - data
  data:
    image: busybox:latest
    volumes:
      - /var/lib/data/mariadb:/var/lib/mysql
  rancher-server:
    image: rancher/server:v1.1.0-dev5
    restart: always
    depends_on:
      - mariadb
    links:
      - mariadb
    environment:
      CATTLE_DB_CATTLE_MYSQL_HOST: mariadb
    ports:
      - "8080:8080"