version: '2'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: cattle 
      MYSQL_USER: cattle
      MYSQL_PASSWORD: cattle
    #   MYSQL_ROOT_PASSWORD: 
    ports:
      - "3036:3036"
    volumes_from:
      - mysql_data
  mysql_data:
    image: busybox:latest
    volumes:
      - /var/lib/data/mysql:/var/lib/mysql
  rancher-server:
    image: rancher/server:v1.1.0-dev5
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      CATTLE_DB_CATTLE_MYSQL_HOST: mysql
    ports:
      - "8080:8080"