version: '2'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/data/mysql:/var/lib/mysql
    volumes_from:
      - mysql_data
  mysql_data:
    image: busybox:latest
    volumes:
      - /var/lib/data/mysql:/var/lib/mysql