version: '2'
services:
  cassandra:
    image: cassandra:2.2
    restart: always
    ports:
      - "9042:9042"
    volumes_from:
      - cassandra_data
  cassandra_data:
    image: busybox:latest
    volumes:
      - /var/lib/cassandra
  kong:
    image: littlebaydigital/kong:0.8.3
    restart: always
    depends_on:
      - cassandra
    links:
      - cassandra
    environment:
      DATABASE: cassandra
      CASSANDRA_CONTACT_POINTS: '\"cassandra:9042\"'
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
  kong-dashboard:
    image: pgbi/kong-dashboard:latest
    restart: always
    depends_on:
      - kong
    ports:
      - "9090:8080"